import {
  Home,
  Sparkles,
  FileText,
  ShieldCheck,
  TrendingUp,
  HeartPulse,
  Target,
  Clock,
  Car,
  Building2,
  Cog,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  home: Home,
  sparkles: Sparkles,
  file: FileText,
  shield: ShieldCheck,
  "trending-up": TrendingUp,
  heart: HeartPulse,
  target: Target,
  clock: Clock,
  car: Car,
  building: Building2,
  cog: Cog,
  wrench: Wrench,
};
